// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYs6jAHQD2dtK5sXNwHm8xFejVnt-2elE',
    appId: '1:762035027476:web:6630798d5503b287a77101',
    messagingSenderId: '762035027476',
    projectId: 'moviles20261-57c47',
    authDomain: 'moviles20261-57c47.firebaseapp.com',
    storageBucket: 'moviles20261-57c47.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm0WtI7XnSjBgVZJEnvLsS2JRLfu4wuHw',
    appId: '1:762035027476:android:84f67256385ac387a77101',
    messagingSenderId: '762035027476',
    projectId: 'moviles20261-57c47',
    storageBucket: 'moviles20261-57c47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeMYQiHBErmLsDvc_rXBMZYnrMuVfmw-s',
    appId: '1:762035027476:ios:ce10f380a7d5747fa77101',
    messagingSenderId: '762035027476',
    projectId: 'moviles20261-57c47',
    storageBucket: 'moviles20261-57c47.firebasestorage.app',
    iosBundleId: 'com.example.electiva2026',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeMYQiHBErmLsDvc_rXBMZYnrMuVfmw-s',
    appId: '1:762035027476:ios:ce10f380a7d5747fa77101',
    messagingSenderId: '762035027476',
    projectId: 'moviles20261-57c47',
    storageBucket: 'moviles20261-57c47.firebasestorage.app',
    iosBundleId: 'com.example.electiva2026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYs6jAHQD2dtK5sXNwHm8xFejVnt-2elE',
    appId: '1:762035027476:web:dd612ae94e1dfe76a77101',
    messagingSenderId: '762035027476',
    projectId: 'moviles20261-57c47',
    authDomain: 'moviles20261-57c47.firebaseapp.com',
    storageBucket: 'moviles20261-57c47.firebasestorage.app',
  );
}
